'backend:
  name: git-gateway
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: dhfjtop8x
    api_key: 177524276612323

media_folder: assets/img
public_folder: assets/img

collections:
  - name: "legendas"
    label: "Legendas das Fotos"
    files:
      - name: "Editorial-makeup"
        label: "Editorial Makeup"
        file: "content/Editorial-makeup.json"
        fields:
          - name: fotos
            label: Fotos
            widget: list
            fields:
              - { label: "Foto", name: "arquivo", widget: "image", media_library: { config: { folder: "Editorial-makeup" } } }
              - { label: "Legenda", name: "legenda", widget: "string", required: false }
              - { label: "Layout", name: "tipo", widget: "select", options: ["multi", "single"], default: "multi" }

      - name: "Editorial-fashion"
        label: "Editorial Fashion"
        file: "content/Editorial-fashion.json"
        fields:
          - name: fotos
            label: Fotos
            widget: list
            fields:
              - { label: "Foto", name: "arquivo", widget: "image", media_library: { config: { folder: "Editorial-fashion" } } }
              - { label: "Legenda", name: "legenda", widget: "string", required: false }
              - { label: "Layout", name: "tipo", widget: "select", options: ["multi", "single"], default: "multi" }

      - name: "Beauty-portraits"
        label: "Beauty Portraits"
        file: "content/Beauty-portraits.json"
        fields:
          - name: fotos
            label: Fotos
            widget: list
            fields:
              - { label: "Foto", name: "arquivo", widget: "image", media_library: { config: { folder: "Beauty-portraits" } } }
              - { label: "Legenda", name: "legenda", widget: "string", required: false }
              - { label: "Layout", name: "tipo", widget: "select", options: ["multi", "single"], default: "multi" }

      - name: "Advertising"
        label: "Advertising"
        file: "content/Advertising.json"
        fields:
          - name: fotos
            label: Fotos
            widget: list
            fields:
              - { label: "Foto", name: "arquivo", widget: "image", media_library: { config: { folder: "Advertising" } } }
              - { label: "Legenda", name: "legenda", widget: "string", required: false }
              - { label: "Layout", name: "tipo", widget: "select", options: ["multi", "single"], default: "multi" }'