backend:
  name: git-gateway
  branch: main

media_folder: assets/img
public_folder: assets/img

collections:
  - name: "legendas"
    label: "Legendas das Fotos"
    files:
      - name: "Editorial-makeup"
        label: "Editorial Makeup"
        file: "content/Editorial-makeup.json"
        fields:
          - name: fotos
            label: Fotos
            widget: list
            fields:
              - { label: "Foto", name: "arquivo", widget: "image", media_folder: "/assets/img/Editorial-makeup", public_folder: "/assets/img/Editorial-makeup" }
              - { label: "Legenda", name: "legenda", widget: "string", required: false }
              - { label: "Layout", name: "tipo", widget: "select", options: ["multi", "single"], default: "multi" }

      - name: "Editorial-fashion"
        label: "Editorial Fashion"
        file: "content/Editorial-fashion.json"
        fields:
          - name: fotos
            label: Fotos
            widget: list
            fields:
              - { label: "Foto", name: "arquivo", widget: "image", media_folder: "/assets/img/Editorial-fashion", public_folder: "/assets/img/Editorial-fashion" }
              - { label: "Legenda", name: "legenda", widget: "string", required: false }
              - { label: "Layout", name: "tipo", widget: "select", options: ["multi", "single"], default: "multi" }

      - name: "Beauty-portraits"
        label: "Beauty Portraits"
        file: "content/Beauty-portraits.json"
        fields:
          - name: fotos
            label: Fotos
            widget: list
            fields:
              - { label: "Foto", name: "arquivo", widget: "image", media_folder: "/assets/img/Beauty-portraits", public_folder: "/assets/img/Beauty-portraits" }
              - { label: "Legenda", name: "legenda", widget: "string", required: false }
              - { label: "Layout", name: "tipo", widget: "select", options: ["multi", "single"], default: "multi" }

      - name: "Advertising"
        label: "Advertising"
        file: "content/Advertising.json"
        fields:
          - name: fotos
            label: Fotos
            widget: list
            fields:
              - { label: "Foto", name: "arquivo", widget: "image", media_folder: "/assets/img/Advertising", public_folder: "/assets/img/Advertising" }
              - { label: "Legenda", name: "legenda", widget: "string", required: false }
              - { label: "Layout", name: "tipo", widget: "select", options: ["multi", "single"], default: "multi" }
